#include<iostream>
using namespace std;
#include<conio.h>
#include<unistd.h>
int main()
{

system("cls");

// cout<<"1. ONE             "<<"11. ELEVEN         "<<"21. TWENTY-ONE       "<<"31. THIRTY-ONE      "<<"41. FORTY-ONE    "<<endl;
// cout<<"2. TWO             "<<"12. TWELVE         "<<"22. TWENTY-TWO       "<<"32. THIRTY-TWO      "<<"42. FORTY-TWO    "<<endl;
// cout<<"3. THREE           "<<"13. THIRTEEN       "<<"23. TWENTY-THREE     "<<"33. THIRTY-THREE    "<<"43. FORTY-THREE  "<<endl;
// cout<<"4. FOUR            "<<"14. FOURTEEN       "<<"24. TWENTY-FOUR      "<<"34. THIRTY-FOUR     "<<"44. FORTY-FOUR   "<<endl;
// cout<<"5. FIVE            "<<"15. FIFTEEN        "<<"25. TWENTY-FIVE      "<<"35. THIRTY-FIVE     "<<"45. FORTY-FIVE   "<<endl;
// cout<<"6. SIX             "<<"16. SIXTEEN        "<<"26. TWENTY-SIX       "<<"36. THIRTY-SIX      "<<"46. FORTY-SIX    "<<endl;
// cout<<"7. SEVEN           "<<"17. SEVENTEEN      "<<"27. TWENTY-SEVEN     "<<"37. THIRTY-SEVEN    "<<"47. FORTY-SEVEN  "<<endl;
// cout<<"8. EIGHT           "<<"18. EIGHTEEN       "<<"28. TWENTY-EIGHT     "<<"38. THIRTY-EIGHT    "<<"48. FORTY-EIGHT  "<<endl;
// cout<<"9. NINE            "<<"19. NINETEEN       "<<"29. TWENTY-NINE      "<<"39. THIRTY-NINE     "<<"49. FORTY-NINE   "<<endl;
// cout<<"10. TEN            "<<"20. TWENTY         "<<"30. THIRTY           "<<"40. FOURTY          "<<"50. FIFTY        "<<endl;

// cout<<"\n\n\n";

// cout<<"51. FIFTY-ONE      "<<"61. SIXTY-ONE      "<<"71. SEVENTY-ONE      "<<"81. EIGHTY-ONE      "<<"91. NINETY-ONE    "<<endl;
// cout<<"52. FIFTY-TWO      "<<"62. SIXTY-TWO      "<<"72. SEVENTY-TWO      "<<"82. EIGHTY-TWO      "<<"92. NINETY-TWO    "<<endl;
// cout<<"53. FIFTY-THREE    "<<"63. SIXTY-THREE    "<<"73. SEVENTY-THREE    "<<"83. EIGHTY-THREE    "<<"93. NINETY-THREE  "<<endl;
// cout<<"54. FIFTY-FOUR     "<<"64. SIXTY-FOUR     "<<"74. SEVENTY-FOUR     "<<"84. EIGHTY-FOUR     "<<"94. NINETY-FOUR   "<<endl;
// cout<<"55. FIFTY-FIVE     "<<"65. SIXTY-FIVE     "<<"75. SEVENTY-FIVE     "<<"85. EIGHTY-FIVE     "<<"95. NINETY-FIVE   "<<endl;
// cout<<"56. FIFTY-SIX      "<<"66. SIXTY-SIX      "<<"76. SEVENTY-SIX      "<<"86. EIGHTY-SIX      "<<"96. NINETY-SIX    "<<endl;
// cout<<"57. FIFTY-SEVEN    "<<"67. SIXTY-SEVEN    "<<"77. SEVENTY-SEVEN    "<<"87. EIGHTY-SEVEN    "<<"97. NINETY-SEVEN  "<<endl;
// cout<<"58. FIFTY-EIGHT    "<<"68. SIXTY-EIGHT    "<<"78. SEVENTY-EIGHT    "<<"88. EIGHTY-EIGHT    "<<"98. NINETY-EIGHT  "<<endl;
// cout<<"59. FIFTY-NINE     "<<"69. SIXTY-NINE     "<<"79. SEVENTY-NINE     "<<"89. EIGHTY-NINE     "<<"99. NINETY-NINE   "<<endl;
// cout<<"60. SIXTY          "<<"70. SEVENTY        "<<"80. EIGHTY           "<<"90. NINTY           "<<"100. HUNDRED      "<<endl;


                    // int a,b ,s ;

                    // cout<<"Enter First No : " ;
                    // cin>>a;
                    // cout<<"Enter Second No : ";
                    // cin>>b;
                    // s=b/a;
                
                    // cout<<b<<" / "<<a<<" = "<<s <<endl<<endl;
                    // getch();
                    // cout<<"Exaples:-"<<endl;
                    // cout<<"\t    "<<a<<" ) "<<b+8<<" ( "<<(b+8)/a<<"\t   "<<a+1<<" ) "<<b+5<<" ( "<<(b+5)/(a+1)<<"\t    "<<a+2<<" ) "<<b+22<<" ( "<<(b+22)/(a+2)<<"\t    "<<a+3<<" ) "<<b+35<<" ( "<<(b+35)/(a+3)<<"\t   "<<a+4<<" ) "<<b+32<<" ( "<<(b+32)/(a+4)<<endl;
 
                    // cout<<"\t        "<<b+8<<"\t       "<<b+5<<"\t        "<<b+22<<"\t        "<<b+35<<"\t       "<<b+32<<"   "<<endl;
                
                    // cout<<"            --------       --------         --------        --------       --------"<<endl;
                    // cout<<"\t        "<<"xx"<<"\t       "<<"xx"<<"\t        "<<"xx"<<"\t        "<<"xx"<<"\t       "<<"xx"<<"   "<<endl;
                    // cout<<"            --------       --------         --------        --------       --------"<<endl;
                    // cout<<endl<<endl;
                    // getch();
                    
                    // cout<<"Revision:"<<endl;

                
                    // int temp;
                    // temp=a;
                    // a=b;
                    // b=temp;

                    // cout<<"\t    "<<a+8<<" ) "<<b+4<<" ( "<<"\t   "<<a+2<<" ) "<<b+6<<" ( "<<"\t    "<<a<<" ) "<<b+4<<" ( "<<"\t    "<<a+1<<" ) "<<b+11<<" ( "<<"\t   "<<a+3<<" ) "<<b+5<<" ( "<<endl;
                    // cout<<endl<<endl;
                    // cout<<"            --------       --------         --------        --------       --------"<<endl;
                    // cout<<"            --------       --------         --------        --------       --------"<<endl;
                    // cout<<endl<<endl;
                    // cout<<"\t    "<<a+30<<" ) "<<b+6<<" ( "<<"\t   "<<a+5<<" ) "<<b+18<<" ( "<<"\t    "<<a+7<<" ) "<<b+71<<" ( "<<"\t    "<<a+3<<" ) "<<b+30<<" ( "<<"\t   "<<a+1<<" ) "<<b+17<<" ( "<<endl;
                    // cout<<endl<<endl;
                    // cout<<"            --------       --------         --------        --------       --------"<<endl;
                    // cout<<"            --------       --------         --------        --------       --------"<<endl;
                    // cout<<endl<<endl;
                    // cout<<"\t     a) "<<a+26<<" / "<<b+2<<" = "<<"\t      b)  "<<a+2<<" / "<<b+4<<" = "<<"\t        c) "<<a+5<<" / "<<b+3<<" = "<<"\t      d) "<<a+54<<" / "<<b+6<<" = "<<endl; 
                    // cout<<endl<<endl;
                    // cout<<"\t     e) "<<a+39<<" / "<<b+5<<" = "<<"\t      f)  "<<a+14<<" / "<<b+2<<" = "<<"\t        g) "<<a+15<<" / "<<b+3<<" = "<<"\t      h) "<<a+11<<" / "<<b+5<<" = "<<endl; 
                    // cout<<endl<<endl;
                    // cout<<"\t     i) "<<a+70<<" / "<<b+6<<" = "<<"\t      j)  "<<a+22<<" / "<<b+4<<" = "<<"\t        k) "<<a+17<<" / "<<b+1<<" = "<<"\t      l) "<<a+35<<" / "<<b+7<<" = "<<endl;  

                    // cout<<endl;

                    float i;
                    int n[10];
                    cout<<"table of ";
                    cin>>n;
                    for(i=1;i<=10;i++)
                    {
                        cout<<n<<" * "<<i<<" = "<<n[0]*i<<endl;
                        sleep(2);
                    }
                          


//getch();
return 0;
}